export const DEFAULT_CATEGORIES = [
  "Faculty News",
  "Exam Updates",
  "Student Life",
  "Health",
  "Opinion",
  "News",
  "Breaking News",
  "Features",
  "Politics",
  "Entertainment",
  "Poem",
  "Satire",
  "Vox-Pop",
  "Interview",
  "Exclusive Interview",
  "Fashion",
  "Culture",
  "Sports",
];